package model;

public enum EnumtipoAreaAtuacao {

    MARKTING,
    ANALISTADESISTEMA,
    DIREITOEMPRESARIAL,
    GESTAOFINANCEIRA,
    MENTOREMINOVACAO,
    EDUCAOPARAMIDIAS,
    QA,
    DESENVOLVEDORBACKEND,
    DESENVOLVEDORFRONTEND,
    ANALISTADENEGOCIO,
    PO,
    SCRUMMASTER


}
